apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: todo-react
  annotations:
    cost-insights.microsoft.com/resource-group: "rg-my-service"
  title: To-do in React
  description: A web-based To-do application, written in React. For demonstration purposes only!
  tags:
    - react
    - website
spec:
  type: service
  lifecycle: experimental
  owner: dev-support
